export const CHANGE_ACTIVE_PAGE_GROUP_PK = 'CHANGE_ACTIVE_PAGE_GROUP_PK';
export const CHANGE_ACTIVE_FORMDATA = 'CHANGE_ACTIVE_FORMDATA';
export const ENABLE_UPDATE_CONTENT = 'ENABLE_UPDATE_CONTENT';
export const DISABLE_UPDATE_CONTENT = 'DISABLE_UPDATE_CONTENT';